spring:
  application:
    name: Finance_Tracker

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:finance}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
    ru.vgd.tracker: DEBUG
    org.zalando.logbook: DEBUG
    # org.springframework.orm.jpa.JpaTransactionManager: DEBUG

  file:
    name: logs/${spring.application.name}.log
    logback:
      rollingpolicy:
        max-file-size: 10MB
        file-name-pattern: logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
        max-history: 30