spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wallet_dev
    username: postgres
    password: password

  web:
    error:
      include-message: always
      include-stacktrace: always
      include-exception: true

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false

logging:
  level:
    ru.vgd.tracker: DEBUG
    org.zalando.logbook: DEBUG
