spring:
  application:
    name: Finance_Tracker

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:finance}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  thymeleaf:
    cache: false
